#!/bin/sh

# Padding
bspc config top_padding $PANEL_HEIGHT

# Borders and gaps
bspc config border_width 0
bspc config window_gap 30
bspc config borderless_monocle false
bspc config gapless_monocle true

# Border colors
bspc config normal_border_color "#11361E"
#bspc config normal_private_border_color "#888888"
bspc config focused_border_color "#B8880C"
bspc config urgent_border_color "#b58900"
# It looks like these options get overridden by Compton...
bspc config normal_frame_opacity 0
bspc config focused_frame_opacity 0.5

# Multihead behavior
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true

# Focusing behavior
bspc config focus_follows_pointer false
bspc config history_aware_focus true

# Misc
bspc config split_ratio 0.50
bspc config auto_alternate true
bspc config auto_cancel true

# Set up displays
bspc monitor --reset-desktops 1
bspc monitor --add-desktops 2
bspc monitor --add-desktops 3
bspc monitor --add-desktops 4

bspc rule -a higan manage=off floating=on
bspc rule -a znes fullscreen=on
bspc rule -a oblogout floating=on fullscreen=on
bspc rule -a tint2 floating=on manage=off
bspc rule -a Wicd-client.py floating=on
bspc rule -a gbacklight floating=on
bspc rule -a lxappearance floating=on
bspc rule -a chrome_app_list floating=on
bspc rule -a Galculator floating=on